- name: Install guake and guake-preferences
  become: true
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - dconf-cli
      - dconf-editor
      - guake
    state: present

- name: Save guake preferences
  become: false
  ansible.builtin.shell: guake --save-preferences {{role_path}}/files/guake-prefs
  when: save_guake_prefs|default(false)

- name: Restore guake preferences
  become: false
  ansible.builtin.shell: guake --restore-preferences {{role_path}}/files/guake-prefs
  when: restore_guake_prefs|default(false)
