# - name: "Playing with Ansible and Git"
#   hosts: localhost
#   connection: local 
#   tasks:

#   - name: "just execute a ls -lrt command"
#     shell: "ls -lrt"
#     register: "output"

#   - debug: var=output.stdout_lines
- name: Install apt packages
  hosts: localhost
  connection: local
  roles:
  - guake
  - xkeysnail
  - dotfiles
  tasks:
  - name: apt update
    become: true
    ansible.builtin.apt:
      update_cache: yes
  - name: personal-use software
    become: true
    ansible.builtin.apt:
      update_cache: yes
      pkg:
      - curl
      - vim
      - dnsmasq
      - nodejs
      - npm
      - jq
      - tmux
      - gnome-keyring
      - git
      - python3-pip
      - xclip
      state: present
    tags:
    - software
  - name: imagr software
    become: true
    ansible.builtin.apt:
      pkg:
      - wireguard
  - name: Japanese keyboard
    ansible.builtin.apt:
      pkg:
      - fcitx5-mozc
  - name: vim as default editor
    tags:
    - vim
    - software
    block:
    - ansible.builtin.shell: realpath $(which vim)
      register: vim_path
    - community.general.alternatives:
        name: editor
        path: "{{ vim_path.stdout }}"
      become: true