- name: Install and configure xkeysnail
  become: true
  block:
    - ansible.builtin.apt:
        update_cache: true
        cache_valid_time: "{{ apt_cache_valid_time }}"
        pkg:
          - pipx
        state: present

    - ansible.builtin.shell: /usr/bin/pipx ensurepath

    - name: Install xkeysnail pip package
      community.general.pipx:
        executable: /usr/bin/pipx
        name: xkeysnail

    - name: Xkeysnail systemd service definition
      ansible.builtin.copy:
        dest: /etc/systemd/system/xkeysnail.service
        mode: "644"
        content: |
          [Unit]
          Description=xkeysnail

          [Service]
          Environment="DISPLAY=:0"
          ExecStartPre=/usr/bin/sudo -u {{ ansible_user_id }} /usr/bin/xhost +SI:localuser:root
          Type=simple
          ExecStart=/root/.local/bin/xkeysnail --watch --quiet {{ role_path }}/files/config.py
          ExecStop=/bin/kill -TERM $MAINPID
          Restart=always
          RestartSec=5

          [Install]
          WantedBy=graphical.target

    - name: Enable xkeysnail service
      ansible.builtin.systemd:
        daemon_reload: true
        name: xkeysnail
        enabled: true
        state: started
