# https://unix.stackexchange.com/a/315400
- name: Turn off wifi power management
  become: true
  block:
    - name: Turn wifi power management off
      community.general.ini_file:
        path: /etc/NetworkManager/conf.d/default-wifi-powersave-on.conf
        section: connection
        option: wifi.powersave
        value: 2
        backup: false
        create: true
        mode: "644"
      notify: Restart NetworkManager
