- name: Create undervolt service and timer
  become: true
  block:
    - name: Install undervolt pip package
      ansible.builtin.pip:
        executable: pip3
        name: undervolt
        state: present

    - name: Create systemd service definition
      ansible.builtin.copy:
        dest: /etc/systemd/system/
        src: "{{ item }}"
        mode: "644"
      with_fileglob: "{{ role_path }}/files/undervolt.*"

    - name: Enable and start undervolt service
      ansible.builtin.systemd:
        daemon_reload: true
        name: "{{ item }}"
        enabled: true
        state: started
      with_items:
        - undervolt
        - undervolt.timer
