- name: Create undervolt service and timer
  become: true
  block:
    - ansible.builtin.apt:
        update_cache: true
        cache_valid_time: "{{ apt_cache_valid_time }}"
        pkg:
          - pipx
        state: present

    - ansible.builtin.shell: /usr/bin/pipx ensurepath

    - name: Install xkeysnail pip package
      community.general.pipx:
        executable: /usr/bin/pipx
        name: undervolt

    - name: Create systemd service definition
      ansible.builtin.copy:
        dest: /etc/systemd/system/
        src: "{{ item }}"
        mode: "644"
      with_fileglob: "{{ role_path }}/files/undervolt.*"

    - name: Enable and start undervolt service
      ansible.builtin.systemd:
        daemon_reload: true
        name: "{{ item }}"
        enabled: true
        state: started
      with_items:
        - undervolt
        - undervolt.timer
